### ISSUE TITLE
Wallet service not starting 

### ISSUE THREAD

**Issue by xavier506** [eoscostarica/eosio-dashboard#101]
info  2020-08-21T16:32:54.484 keosd     wallet_plugin.cpp:38          plugin_initialize    ] initializing wallet plugin
warn  2020-08-21T16:32:54.484 keosd     wallet_plugin.cpp:64          plugin_initialize    ] 3120000 wallet_exception: Wallet exception
Failed to open wallet lock file at /opt/application/data/./wallet.lock
    {"f":"/opt/application/data/./wallet.lock"}
    keosd  wallet_manager.cpp:299 initialize_lock
Failed to initialize

**Comment by kuronosec** [comment]
Thanks @adriexnet . The "db_data" is not necessary since k8s does mount a volume for it in the NFS server. On the other hand, is "wallet_data" something we have to persist? What happens if we start a fresh wallet service every time? If we need persistence, then I can create a volume in NFS. If we don't, then we only need a "data" directory inside wallet directory.
